name: Build Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install Arduino Core
      run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

    - name: Install Arduino Libraries
      run: |
          arduino-cli lib update-index
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit ST7735 and ST7789 Library"

    - name: Compile and Export Binary
      run: |
        arduino-cli compile --fqbn arduino:avr:nano --output-dir build --export-binaries ./firmware/JBCNano

    - name: Generate timestamp
      id: vars
      run: echo "DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ env.DATE }}
        path: build/
